openapi: 3.0.3
info:
  title: Warehouse
  description: |-
    This is for a demo application
  contact:
    email: info@maxmayr.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Github repo
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: Article
    description: Article based endpoints
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /articles:
    get:
      tags:
        - Article
      summary: Get a list of Articles based on your search
      description: Search for an article
      operationId: searchArticle
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ArticleSearchResponse'
                  - $ref: '#/components/schemas/PaginatedResult'
components:
  schemas:
    PaginatedResult:
      type: object
      properties:
        totalElements:
          type: number
        totalPages:
          type: number
        page:
          type: number
        size:
          type: number
    Article:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Gear"
          description: Article name
        description:
          type: string
          example: "A gear"
          description: Article description
        createdAt:
          type: string
          format: date-time
        complete:
          type: boolean
    ArticleSearchResponse:
      description: Article search result
      type: object
      required:
        - content
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Article'
          description: |
            A list of Article objects